#!/bin/bash

# This Script will add the current SSID to the UNSAFE_SSIDS file and
# then runs the main WallAware script. If the SSID is already added
# the main WallAware script is ran.

SSID=$(networksetup -getairportnetwork en0 | sed -E 's,^Current Wi-Fi Network: (.+)$,\1,')

if grep -Fxq "$SSID" ~/WallAware/UNSAFE_SSIDS.txt
then
  
    echo
    echo --------------------------------
    echo "$SSID" Already added. Switching to clean wallpaper now!
    echo --------------------------------
    echo

    sh ~/WallAware/WallAware.sh
else
    networksetup -getairportnetwork en0 | sed -E 's,^Current Wi-Fi Network: (.+)$,\1,' >> ~/WallAware/UNSAFE_SSIDS.txt

    echo
    echo --------------------------------
    echo "$SSID" has been added as an unsafe network. Switching to clean wallpaper now!
    echo --------------------------------
    echo

    sh ~/WallAware/WallAware.sh
fi

exit 0;
